//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvsyssel_Kund_Register.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KundRegister
    {
        public int Kund_Id { get; set; }
        public string Kund_Fornamn { get; set; }
        public string Kund_Efternamn { get; set; }
        public Nullable<int> Produkt_id { get; set; }
        public Nullable<System.DateTime> Datum_kop { get; set; }
        public Nullable<System.DateTime> Datum_installation { get; set; }
        public Nullable<int> Kund_telefon_nr { get; set; }
        public string Kund_e_mail { get; set; }
        public string Kund_adress { get; set; }
        public Nullable<int> Kund_post_nr { get; set; }
        public string Kund_region { get; set; }
        public byte[] Medgivande_att_bli_kontaktad { get; set; }
        public Nullable<int> Admin_id { get; set; }
        public Nullable<System.DateTime> Senast_andrad { get; set; }
        public Nullable<int> Order_nr { get; set; }
        public string Produkt_typ { get; set; }
        public string GDPR__Medgivande { get; set; }
        public string C30_Dagar { get; set; }
    }
}
